

zimug:
  gateway:
    jwt:
      enabled: true   #是否开启JWT登录认证功能
      secret: fjkfaf;afa  # JWT私钥，用于校验JWT令牌的合法性
      expiration: 3600000 #JWT令牌的有效期，用于校验JWT令牌的合法性
      header: JWTHeaderName #HTTP请求的Header名称，该Header作为参数传递JWT令牌
      userParamName: username  #用户登录认证用户名参数名称
      pwdParamName: password  #用户登录认证密码参数名称
      useDefaultController: true # 是否使用默认的JwtAuthController
server:
  port: 8088

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root